#!/usr/bin/env bash
set -euo pipefail

# pauto_report.sh (SAFE mode: AUTO_PUSH=true)
# Usage: pauto_report.sh [path-to-scan-file]
# If no arg provided -> picks latest .nmap in scans dir

BASE="$HOME/Projects/ProPlus/security_tools"
SCANS_DIR="$BASE/scans"
REPORTS_DIR="$BASE/docs/reports"
GIT_REPO_DIR="$BASE"

mkdir -p "$REPORTS_DIR"

# choose file
SCAN_FILE="${1:-}"
if [ -z "$SCAN_FILE" ]; then
  # prefer latest .nmap, else .xml, else .gnmap
  SCAN_FILE="$(ls -1t "$SCANS_DIR"/*.nmap 2>/dev/null | head -n1 || true)"
  if [ -z "$SCAN_FILE" ]; then
    SCAN_FILE="$(ls -1t "$SCANS_DIR"/*.xml 2>/dev/null | head -n1 || true)"
  fi
  if [ -z "$SCAN_FILE" ]; then
    SCAN_FILE="$(ls -1t "$SCANS_DIR"/*.gnmap 2>/dev/null | head -n1 || true)"
  fi
fi

if [ -z "$SCAN_FILE" ] || [ ! -f "$SCAN_FILE" ]; then
  echo "No scan file found in $SCANS_DIR. Place .nmap/.xml/.gnmap files there." >&2
  exit 1
fi

FNAME="$(basename "$SCAN_FILE")"
TS="$(date +%Y%m%d_%H%M%S)"
TARGET_SAFE="$(echo "$FNAME" | sed -E 's/^scan_//; s/[^a-zA-Z0-9._-]/_/g' | sed -E 's/_[0-9]{8}_[0-9]{6}.*$//')"
REPORT_FN="${REPORTS_DIR}/${TS}__${TARGET_SAFE}.md"

# parse common pieces
HOST_LINE="$(grep -m1 -E '^Nmap scan report for ' "$SCAN_FILE" || true)"
HOST="$(echo "$HOST_LINE" | sed -E 's/^Nmap scan report for //')"

HDR_TS="$(grep -m1 '^# Nmap ' "$SCAN_FILE" | sed -n '1p' || true)"

PORTS="$(grep -E '^[0-9]+/tcp' "$SCAN_FILE" || true)"
HTTP_TITLE="$(grep -m1 -i 'http-title:' "$SCAN_FILE" | sed -E 's/^[[:space:]]*\|?_?http-title: ?//I' || true)"
SSL_CERT="$(grep -m1 -i 'ssl-cert:' -A2 "$SCAN_FILE" | tr '\n' ' ' | sed -E 's/.*ssl-cert: ?//I' || true)"

OPEN_COUNT="$(echo "$PORTS" | grep -c '^' || true)"
if [ -z "$OPEN_COUNT" ]; then OPEN_COUNT=0; fi

cat > "$REPORT_FN" <<EOF
# ProPlus Scan Report — ${TARGET_SAFE}
**Scan file:** \`${FNAME}\`  
**Generated:** $(date -u +"%Y-%m-%d %H:%M:%SZ") (UTC)  
**Scan header:** ${HDR_TS:-"N/A"}  

## Host
\`\`\`
${HOST:-Unknown}
\`\`\`

## Summary
- Open ports found: **${OPEN_COUNT}**
- HTTP Title: **${HTTP_TITLE:-N/A}**
- SSL Certificate summary: **${SSL_CERT:-N/A}**

## Open ports (raw)
\`\`\`
${PORTS:-None}
\`\`\`

## Full nmap raw (excerpt)
\`\`\`
$(sed -n '1,200p' "$SCAN_FILE")
\`\`\`

---

*Generated by ProPlus pauto_report.sh (safe mode)*
EOF

echo "[*] Report saved to: $REPORT_FN"

# SAFE MODE: do NOT auto push to remote
AUTO_PUSH=true

if [ "$AUTO_PUSH" = "true" ]; then
  if command -v git >/dev/null 2>&1 && [ -d "$GIT_REPO_DIR/.git" ]; then
    (
      cd "$GIT_REPO_DIR"
      git add "$REPORT_FN" || true
      git commit -m "Add scan report: ${TS} ${TARGET_SAFE}" || true
      git push origin main || true
    )
    echo "[*] Report committed and pushed (if remote configured)."
  else
    echo "[!] Git not available or repo missing - skipping git push."
  fi
else
  echo "[*] AUTO_PUSH is disabled (safe mode). Report created locally; to commit & push, run:"
  echo "    cd \"$GIT_REPO_DIR\" && git add \"$REPORT_FN\" && git commit -m \"Add scan report: ${TS} ${TARGET_SAFE}\" && git push"
fi

exit 0
